{{- if eq .chezmoi.os "windows" }}
# Windows: navi cheats at AppData/Roaming/navi/cheats/
["AppData/Roaming/navi/cheats/docker.cheat"]
    type = "file"
    url = "https://github.com/denisidoro/cheats/raw/addb1ea64acaf55f8958d77dfa9e2a9379ab4d28/container/docker.cheat"
["AppData/Roaming/navi/cheats/kubernetes.cheat"]
    type = "file"
    url = "https://github.com/denisidoro/cheats/raw/addb1ea64acaf55f8958d77dfa9e2a9379ab4d28/container/kubernetes.cheat"
["AppData/Roaming/navi/cheats/git.cheat"]
    type = "file"
    url = "https://github.com/denisidoro/cheats/raw/addb1ea64acaf55f8958d77dfa9e2a9379ab4d28/code/git.cheat"

["AppData/Roaming/nushell/nu_scripts"]
    type = "git-repo"
    url = "https://github.com/nushell/nu_scripts"

{{- else }}
# Linux: navi cheats at .local/share/navi/cheats/
[".local/share/navi/cheats/brew.cheat"]
    type = "file"
    url = "https://github.com/denisidoro/cheats/raw/addb1ea64acaf55f8958d77dfa9e2a9379ab4d28/pkg_mgr/apt.cheat"
[".local/share/navi/cheats/apt.cheat"]
    type = "file"
    url = "https://github.com/denisidoro/cheats/raw/addb1ea64acaf55f8958d77dfa9e2a9379ab4d28/pkg_mgr/brew.cheat"
[".local/share/navi/cheats/javascript.cheat"]
    type = "file"
    url = "https://github.com/denisidoro/cheats/raw/addb1ea64acaf55f8958d77dfa9e2a9379ab4d28/pkg_mgr/javascript.cheat"
[".local/share/navi/cheats/curl.cheat"]
    type = "file"
    url = "https://github.com/denisidoro/cheats/raw/addb1ea64acaf55f8958d77dfa9e2a9379ab4d28/network/curl.cheat"
[".local/share/navi/cheats/network.cheat"]
    type = "file"
    url = "https://github.com/denisidoro/cheats/raw/addb1ea64acaf55f8958d77dfa9e2a9379ab4d28/network/network.cheat"
[".local/share/navi/cheats/docker.cheat"]
    type = "file"
    url = "https://github.com/denisidoro/cheats/raw/addb1ea64acaf55f8958d77dfa9e2a9379ab4d28/container/docker.cheat"
[".local/share/navi/cheats/kubernetes.cheat"]
    type = "file"
    url = "https://github.com/denisidoro/cheats/raw/addb1ea64acaf55f8958d77dfa9e2a9379ab4d28/container/kubernetes.cheat"
[".local/share/navi/cheats/git.cheat"]
    type = "file"
    url = "https://github.com/denisidoro/cheats/raw/addb1ea64acaf55f8958d77dfa9e2a9379ab4d28/code/git.cheat"

[".local/bin/ssh-ident"]
    type = "file"
    url = "https://raw.githubusercontent.com/ccontavalli/ssh-ident/66a00104057411d85592411455261284d08bb065/ssh-ident"
    executable = true

[".config/zsh/zsh-autocomplete"]
    type = "git-repo"
    url = "https://github.com/marlonrichert/zsh-autocomplete.git"
{{- end }}
